-- Dashboard pipeline stages: a second, per-destination pipeline distinct
-- from destinations.pipeline_stages (which tracks a single APPLICATION's
-- progress at a specific university). This one tracks the registered
-- STUDENT's overall progress toward a destination as a country-level
-- milestone list (Admission Docs, Visa Status, Travel, Enrollment, ...),
-- shared across every application they have to that country — set by staff,
-- shown read-only to the student on their own portal dashboard.
--
-- Each stage is {key, label, type, options}: type "checkbox" (options has
-- exactly one value, e.g. "Completed" — staff just marks it done or not),
-- "select" (options has 2+ values, e.g. Visa Status: Granted/Rejected —
-- staff picks one), or "date" (a date field, e.g. Travel: Date).
--
-- dashboard_stage_values on lead_destinations holds the actual per-student
-- answers as {stage_key: value}; a key's absence means that stage hasn't
-- been reached/set yet — same "first unset stage = current" logic as the
-- existing pipeline_stages/current_stage pair, just jsonb-object-shaped
-- instead of a single string, since each stage can carry which option was
-- picked (not just done/not-done).

alter table destinations
  add column if not exists dashboard_pipeline_stages jsonb not null default '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb;

alter table lead_destinations
  add column if not exists dashboard_stage_values jsonb not null default '{}'::jsonb;

-- Seed the exact per-country stage lists from the doc, for the real
-- destinations already on file. Matched by country_code — every other
-- destination (any track, any country not listed here) keeps the standard
-- default set above.

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"scholarship_docs","label":"Scholarship Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'IT';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"blocked_account","label":"Blocked Account","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Parked in Waiting list"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment_2","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'DE';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'FR';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"legalization_appt","label":"Legalization Appt.","type":"select","options":["Booked","In progress","Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'AT';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"ats","label":"ATS","type":"select","options":["Applied","Granted","Rejected"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'LU';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'FI';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"invitation_letter","label":"Invitation Letter","type":"select","options":["In progress","Received"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'RO';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'HU';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"credibility_interview","label":"Credibility Interview","type":"select","options":["Booked","Passed","Failed"]},{"key":"tuition_fee","label":"Tuition Fee","type":"select","options":["Paid","Unpaid"]},{"key":"cas","label":"CAS","type":"select","options":["Issued","Rejected"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_interview","label":"Visa Interview","type":"select","options":["Passed","Fail"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'UK';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"tuition_fee","label":"Tuition Fee","type":"select","options":["Paid","Unpaid"]},{"key":"i20","label":"I20","type":"select","options":["Issued","Rejected"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_interview","label":"Visa Interview","type":"select","options":["Passed","Fail"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'US';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"tuition_fee","label":"Tuition Fee","type":"select","options":["Paid","Unpaid"]},{"key":"loa","label":"LOA","type":"select","options":["Issued","Rejected"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"biometrics_appt","label":"Biometrics Appt","type":"checkbox","options":["Booked"]},{"key":"appointment","label":"Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'CA';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"gs","label":"GS","type":"select","options":["Passed","Rejected"]},{"key":"tuition_fee","label":"Tuition Fee","type":"select","options":["Paid","Unpaid"]},{"key":"coe","label":"COE","type":"select","options":["Issued","Rejected"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"medical","label":"Medical","type":"select","options":["Appt. Booked","Completed","Issued"]},{"key":"biometrics_appt","label":"Biometrics Appt.","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'AU';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"university_and_program","label":"University & Program","type":"checkbox","options":["Selection Finalized"]},{"key":"offer_of_place","label":"Offer of Place","type":"select","options":["Issued","Rejected"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"aip","label":"AIP","type":"select","options":["Granted","Rejected"]},{"key":"tuition_fee","label":"Tuition Fee","type":"select","options":["Paid","Unpaid"]},{"key":"medical","label":"Medical","type":"select","options":["Appt. Booked","Completed","Issued"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'NZ';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"tuition_fee","label":"Tuition Fee","type":"select","options":["Paid","Unpaid"]},{"key":"acceptance_letter","label":"Acceptance Letter","type":"select","options":["Issued","Rejected"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"visa_appointment","label":"Visa Appointment","type":"checkbox","options":["Booked"]},{"key":"visa_app","label":"Visa App","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'TR';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"tuition_fee","label":"Tuition Fee","type":"select","options":["Paid","Unpaid"]},{"key":"acceptance_letter","label":"Acceptance Letter","type":"select","options":["Issued","Rejected"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"medical_appt","label":"Medical Appt","type":"select","options":["Booked","Pending"]},{"key":"visa_appt","label":"Visa Appt.","type":"checkbox","options":["Booked"]},{"key":"visa_appt_2","label":"Visa Appt.","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'NC';

update destinations set dashboard_pipeline_stages = '[{"key":"admission_docs","label":"Admission Docs","type":"checkbox","options":["Completed"]},{"key":"admission","label":"Admission","type":"select","options":["In process","Issued"]},{"key":"tuition_fee","label":"Tuition Fee","type":"select","options":["Paid","Unpaid"]},{"key":"acceptance_letter","label":"Acceptance Letter","type":"select","options":["Issued","Rejected"]},{"key":"visa_docs","label":"Visa Docs","type":"checkbox","options":["Completed"]},{"key":"visa_appt","label":"Visa Appt.","type":"checkbox","options":["Booked"]},{"key":"visa_appt_2","label":"Visa Appt.","type":"checkbox","options":["Submitted"]},{"key":"visa_status","label":"Visa Status","type":"select","options":["Granted","Rejected"]},{"key":"travel","label":"Travel","type":"date","options":[]},{"key":"enrollment","label":"Enrollment","type":"checkbox","options":["Completed"]}]'::jsonb where country_code = 'IE';
